; Frames — EN_CARNAVAL
!EN_CARNAVAL_FRAME_COUNT = 14
!EN_CARNAVAL_TILES_PER_FRAME = 4

!FR_en_carnaval_idle_D_0 = 0  ; frame 0
!FR_en_carnaval_idle_U_0 = 2  ; frame 1
!FR_en_carnaval_idle_L_0 = 4  ; frame 2
!FR_en_carnaval_idle_R_0 = 6  ; frame 3
!FR_en_carnaval_walk_D_0 = 8  ; frame 4
!FR_en_carnaval_walk_D_1 = 10  ; frame 5
!FR_en_carnaval_walk_U_0 = 12  ; frame 6
!FR_en_carnaval_walk_U_1 = 14  ; frame 7
!FR_en_carnaval_walk_L_0 = 16  ; frame 8
!FR_en_carnaval_walk_L_1 = 18  ; frame 9
!FR_en_carnaval_walk_R_0 = 20  ; frame 10
!FR_en_carnaval_walk_R_1 = 22  ; frame 11
!FR_en_carnaval_die_D_0 = 24  ; frame 12
!FR_en_carnaval_die_D_1 = 26  ; frame 13
